name: Build and Publish isci.abbild linux-x64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: '408b7f8b/isci'
        path: 'isci'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      working-directory: ./isci.abbild
      run: dotnet restore      
      
    - name: Build linux-x64
      working-directory: ./isci.abbild
      run: dotnet publish -c Release -r linux-x64 -o ./tmp
      
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: ./isci/.abbild/tmp
        
  docker-build:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download linux-x64 artifact
      uses: actions/download-artifact@v3
      with:
        name: linux-x64
        
    - name: Build and push linux-x64 image
      run: |
        docker build -t isci.abbild:linux-x64 --platform=linux/x64 .
